name: kite-prod

services:
  frontend:
    build:
      context: ../../..
      dockerfile: apps/infra/prod/Dockerfile.frontend
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL:-http://localhost:3001}
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    build:
      context: ../../..
      dockerfile: apps/infra/prod/Dockerfile.backend
    ports:
      - '3001:3001'
    env_file:
      - ./.env.prod.backend
    depends_on:
      - postgres
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kite
      POSTGRES_PASSWORD: kite
      POSTGRES_DB: kite
    volumes:
      - kite-postgres-data:/var/lib/postgresql/data

volumes:
  kite-postgres-data:
